version: '3.8'

services:
  app:
    build:
      context: .
      target: builder
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host
    environment:
      - NODE_ENV=development